### ISSUE TITLE
ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by oliverlietz** [ist-dresden/composum#128]
```
30.03.2018 22:48:48.952 *ERROR* [0:0:0:0:0:0:0:1 [1522442928947] GET /bin/cpm/nodes/property.map.json/ HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.composum.sling.core.util.JsonUtil.writeJsonValue(JsonUtil.java:896) [com.composum.core.commons:1.8.2]
	at com.composum.sling.core.util.JsonUtil.writeJsonProperty(JsonUtil.java:827) [com.composum.core.commons:1.8.2]
	at com.composum.sling.core.util.JsonUtil.writeJsonValueMap(JsonUtil.java:729) [com.composum.core.commons:1.8.2]
	at com.composum.sling.nodes.servlet.PropertyServlet$MapGetOperation.doIt(PropertyServlet.java:147) [com.composum.core.console:1.8.2]
	at com.composum.sling.core.servlet.ServletOperationSet.doGet(ServletOperationSet.java:145) [com.composum.core.commons:1.8.2]
	at com.composum.sling.core.servlet.AbstractServiceServlet.doGet(AbstractServiceServlet.java:75) [com.composum.core.commons:1.8.2]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:266) [org.apache.sling.api:2.18.0]
	at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:137) [org.apache.sling.api:2.18.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:342) [org.apache.sling.api:2.18.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:374) [org.apache.sling.api:2.18.0]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:107) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131) [org.apache.sling.i18n:2.5.12]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151) [org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:234) [org.apache.sling.engine:2.6.12]
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:96) [org.apache.felix.http.sslfilter:1.2.4]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:131) [org.apache.sling.i18n:2.5.12]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.sling.engine.impl.log.RequestLoggerFilter.doFilter(RequestLoggerFilter.java:72) [org.apache.sling.engine:2.6.12]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.sling.engine.impl.parameters.RequestParameterSupportConfigurer.doFilter(RequestParameterSupportConfigurer.java:63) [org.apache.sling.engine:2.6.12]
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:128) [org.apache.felix.http.jetty:3.4.8]
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49) [org.apache.felix.http.jetty:3.4.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [org.apache.felix.http.servlet-api:1.1.2]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [org.apache.felix.http.jetty:3.4.8]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [org.apache.felix.http.jetty:3.4.8]
	at java.lang.Thread.run(Thread.java:748)
```

See [SLING-7565](https://issues.apache.org/jira/browse/SLING-7565)

**Comment by oliverlietz** [comment]
@ist-rw thanks, fixed in 1.8.3 but see #132.
