### ISSUE TITLE
BrowserServlet returns Internal Server Error (500)

### ISSUE THREAD

**Issue by oliverlietz** [ist-dresden/composum#132]
When accessing `/bin/browser.html` for the first time (unauthenticated), `BrowserServlet` returns Internal Server Error (500) due to NPE in `LinkUtil`:

```
2018-04-09T19:10:29,757 | INFO  | qtp73013642-170  | log                              | 121 - org.apache.sling.engine - 2.6.12 | 0:0:0:0:0:0:0:1 - anonymous 09/Apr/2018:19:10:29 +0200 "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
2018-04-09T19:10:34,889 | ERROR | 0:0:0:0:0:0:0:1 [1523293834882] GET /bin/browser.html HTTP/1.1 | SlingRequestProcessorImpl        | 121 - org.apache.sling.engine - 2.6.12 | service: Uncaught Throwable
java.lang.NullPointerException: null
	at com.composum.sling.core.util.LinkUtil.getExtension(LinkUtil.java:342) ~[?:?]
	at com.composum.sling.core.util.LinkUtil.getExtension(LinkUtil.java:299) ~[?:?]
	at com.composum.sling.core.util.LinkUtil.getUrl(LinkUtil.java:136) ~[?:?]
	at com.composum.sling.core.util.LinkUtil.getUrl(LinkUtil.java:94) ~[?:?]
	at com.composum.sling.core.util.LinkUtil.getUrl(LinkUtil.java:45) ~[?:?]
	at com.composum.sling.core.servlet.AbstractConsoleServlet.doGet(AbstractConsoleServlet.java:80) ~[?:?]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:266) ~[106:org.apache.sling.api:2.16.4]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:342) ~[106:org.apache.sling.api:2.16.4]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:374) ~[106:org.apache.sling.api:2.16.4]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:107) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68) ~[121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151) [121:org.apache.sling.engine:2.6.12]
	at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:234) [121:org.apache.sling.engine:2.6.12]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833) [171:org.eclipse.jetty.servlet:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [171:org.eclipse.jetty.servlet:9.4.6.v20170531]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206) [181:org.eclipse.jetty.websocket.server:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [171:org.eclipse.jetty.servlet:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [171:org.eclipse.jetty.servlet:9.4.6.v20170531]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [189:org.ops4j.pax.web.pax-web-jetty:7.0.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [168:org.eclipse.jetty.security:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293) [189:org.ops4j.pax.web.pax-web-jetty:7.0.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [171:org.eclipse.jetty.servlet:9.4.6.v20170531]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [189:org.ops4j.pax.web.pax-web-jetty:7.0.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [170:org.eclipse.jetty.server:9.4.6.v20170531]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [162:org.eclipse.jetty.io:9.4.6.v20170531]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [162:org.eclipse.jetty.io:9.4.6.v20170531]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [162:org.eclipse.jetty.io:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) [173:org.eclipse.jetty.util:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) [173:org.eclipse.jetty.util:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) [173:org.eclipse.jetty.util:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199) [173:org.eclipse.jetty.util:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) [173:org.eclipse.jetty.util:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) [173:org.eclipse.jetty.util:9.4.6.v20170531]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by oliverlietz** [comment]
Composum **`1.8.3`**

**Comment by rombert** [comment]
Would it be possible to release a version with a fix? We keep getting bug reports and mailing list posts on the Sling channels.

Thanks!

**Comment by ist-rw** [comment]
A release 1.8.4 is available now.

**Comment by rombert** [comment]
Great, thanks a lot!
