### ISSUE TITLE
Sling's File System Resource make Composum browser fail with an NPE

### ISSUE THREAD

**Issue by schaefa** [ist-dresden/composum#64]
After setting up a File System Resource with Sling 9 (the latest) browsing the node in Composum's browser fails with an NPE:

Caused by: java.lang.NullPointerException: null
	at com.composum.sling.core.util.LinkUtil.getExtension(LinkUtil.java:334)
	at com.composum.sling.core.util.LinkUtil.getExtension(LinkUtil.java:299)
	at com.composum.sling.nodes.browser.BrowserBean$NodeHandle.getPathUrl(BrowserBean.java:103)
	at com.composum.sling.nodes.browser.BrowserBean.getCurrentPathUrl(BrowserBean.java:153)

I think the reason is because the com.composum.sling.core.ResourceHandle.getPrimaryType() is only using the Node as a way to access it. Unfortunately FsResource cannot be adapted to a resource and hence it returns null.

How to reproduce:

1. Have a folder with JCR nodes
2. In OSGi console's Config Manager search for 'Apache Sling Filesystem Resource Provider'
3. Create an entry by having the absolute path to the JCR Nodes on your disk and the path where it should be added to Sling
4. Open Composum and browse the content. Click on the 'Display Rendered View' button

Cheers - Andy Schaefer

**Comment by ist-rw** [comment]
A fix is available in the 'develop' branch and in the 'release/1.x/v1.7' bugfix branch.

**Comment by schaefa** [comment]
Tested it and works like a charm, thanks.
