### ISSUE TITLE
Exception displaying node types

### ISSUE THREAD

**Issue by mzeibig** [ist-dresden/composum#7]
```
16.10.2015 23:51:14.526 *ERROR* [0:0:0:0:0:0:0:1 [1445032274454] GET /bin/core/node.tree.json/jcr%3Asystem/jcr:nodeTypes/nt:version HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.IllegalStateException: Dangling name: checkedOut
	at com.google.gson.stream.JsonWriter.close(JsonWriter.java:342)
	at com.google.gson.stream.JsonWriter.endObject(JsonWriter.java:317)
	at com.composum.sling.core.servlet.NodeServlet.writeNodeJcrState(NodeServlet.java:1372)
	at com.composum.sling.core.servlet.NodeServlet.writeJsonNode(NodeServlet.java:1229)
	at com.composum.sling.core.servlet.NodeServlet$TreeOperation.doIt(NodeServlet.java:542)
	at com.composum.sling.core.servlet.ServletOperationSet.doGet(ServletOperationSet.java:143)
	at com.composum.sling.core.servlet.AbstractServiceServlet.doGet(AbstractServiceServlet.java:67)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:268)
...
```
(AEM 6.0 OSX)

**Comment by mzeibig** [comment]
reason:

```
16.10.2015 23:51:14.458 *ERROR* [0:0:0:0:0:0:0:1 [1445032274454] GET /bin/core/node.tree.json/jcr%3Asystem/jcr:nodeTypes/nt:version HTTP/1.1] com.composum.sling.core.servlet.NodeServlet /jcr:system/jcr:nodeTypes/nt:version/jcr:childNodeDefinition[1]
javax.jcr.PathNotFoundException: /jcr:system/jcr:nodeTypes/nt:version/jcr:childNodeDefinition[1]
	at org.apache.jackrabbit.oak.jcr.version.VersionManagerImpl$3.perform(VersionManagerImpl.java:260)
	at org.apache.jackrabbit.oak.jcr.version.VersionManagerImpl$3.perform(VersionManagerImpl.java:254)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:308)
	at org.apache.jackrabbit.oak.jcr.version.VersionManagerImpl.isCheckedOut(VersionManagerImpl.java:254)
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.isCheckedOut(NodeImpl.java:1085)
	at com.composum.sling.core.servlet.NodeServlet.writeNodeJcrState(NodeServlet.java:1353)
	at com.composum.sling.core.servlet.NodeServlet.writeJsonNode(NodeServlet.java:1229)
	at com.composum.sling.core.servlet.NodeServlet$TreeOperation.doIt(NodeServlet.java:542)
	at com.composum.sling.core.servlet.ServletOperationSet.doGet(ServletOperationSet.java:143)
	at com.composum.sling.core.servlet.AbstractServiceServlet.doGet(AbstractServiceServlet.java:67)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:268)
	at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:139)
...
```
