### ISSUE TITLE
unclosed resource resolver in package manager 

### ISSUE THREAD

**Issue by reusr1** [ist-dresden/composum#82]
from time to time I get the following exception when installing a package: 

```
*WARN* org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl Closed unclosed ResourceResolver. The creation stacktrace is available on info log level.
*INFO* org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl Unclosed ResourceResolver was created here: 
java.lang.Exception: Opening Stacktrace
	at org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl$ResolverReference.<init>(CommonResourceResolverFactoryImpl.java:514)
	at org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl.register(CommonResourceResolverFactoryImpl.java:217)
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.<init>(ResourceResolverImpl.java:101)
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.<init>(ResourceResolverImpl.java:94)
	at org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl.getResourceResolverInternal(CommonResourceResolverFactoryImpl.java:262)
	at org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl.getResourceResolver(CommonResourceResolverFactoryImpl.java:172)
	at org.apache.sling.resourceresolver.impl.ResourceResolverFactoryImpl.getResourceResolver(ResourceResolverFactoryImpl.java:101)
	at com.composum.sling.core.concurrent.AbstractJobExecutor$UserContextCallable.<init>(AbstractJobExecutor.java:139)
	at com.composum.sling.core.pckgmgr.PackageJobExecutor$PackageManagerCallable.<init>(PackageJobExecutor.java:126)
	at com.composum.sling.core.pckgmgr.PackageJobExecutor.createCallable(PackageJobExecutor.java:118)
	at com.composum.sling.core.concurrent.AbstractJobExecutor.process(AbstractJobExecutor.java:184)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:291)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:58)
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ist-rw** [comment]
Shout be solved with the upcoming release 1.8.
