### ISSUE TITLE
Issue with javax.inject import

### ISSUE THREAD

**Issue by drfits** [ist-dresden/composum#85]
Due to duplication within export packages: ![sling console import output](https://monosnap.com/file/aRoA0BESVAjTqYXYJ6tkf633YJhmo0.png) 

I couldn't install my custom bundle which is using sling models and **javax.inject.Inject** annotations on **Sling launchpad 9 snapshot** :

```
06.06.2017 22:44:58.342 *ERROR* [qtp735192822-47] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Uses constraint violation. Unable to resolve resource meetup-core [meetup-core [154](R 154.1)] because it is exposed to package 'javax.inject' from resources org.apache.geronimo.specs.geronimo-atinject_1.0_spec [org.apache.geronimo.specs.geronimo-atinject_1.0_spec [1](R 1.0)] and com.composum.core.commons [com.composum.core.commons [72](R 72.0)] via two dependency chains.

Chain 1:
  meetup-core [meetup-core [154](R 154.1)]
    import: (&(osgi.wiring.package=javax.inject)(version>=1.0.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package: javax.inject
  org.apache.geronimo.specs.geronimo-atinject_1.0_spec [org.apache.geronimo.specs.geronimo-atinject_1.0_spec [1](R 1.0)]

Chain 2:
  meetup-core [meetup-core [154](R 154.1)]
    import: (&(osgi.wiring.package=org.apache.sling.models.annotations)(version>=1.5.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package=org.apache.sling.models.annotations; uses:=javax.inject
  org.apache.sling.models.api [org.apache.sling.models.api [125](R 125.0)]
    import: (osgi.wiring.package=javax.inject)
     |
    export: osgi.wiring.package: javax.inject
  com.composum.core.commons [com.composum.core.commons [72](R 72.0)] Unresolved requirements: [[meetup-core [154](R 154.1)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.models.annotations)(version>=1.5.0)(!(version>=2.0.0)))])
org.osgi.framework.BundleException: Uses constraint violation. Unable to resolve resource meetup-core [meetup-core [154](R 154.1)] because it is exposed to package 'javax.inject' from resources org.apache.geronimo.specs.geronimo-atinject_1.0_spec [org.apache.geronimo.specs.geronimo-atinject_1.0_spec [1](R 1.0)] and com.composum.core.commons [com.composum.core.commons [72](R 72.0)] via two dependency chains.

Chain 1:
  meetup-core [meetup-core [154](R 154.1)]
    import: (&(osgi.wiring.package=javax.inject)(version>=1.0.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package: javax.inject
  org.apache.geronimo.specs.geronimo-atinject_1.0_spec [org.apache.geronimo.specs.geronimo-atinject_1.0_spec [1](R 1.0)]

Chain 2:
  meetup-core [meetup-core [154](R 154.1)]
    import: (&(osgi.wiring.package=org.apache.sling.models.annotations)(version>=1.5.0)(!(version>=2.0.0)))
     |
    export: osgi.wiring.package=org.apache.sling.models.annotations; uses:=javax.inject
  org.apache.sling.models.api [org.apache.sling.models.api [125](R 125.0)]
    import: (osgi.wiring.package=javax.inject)
     |
    export: osgi.wiring.package: javax.inject
  com.composum.core.commons [com.composum.core.commons [72](R 72.0)] Unresolved requirements: [[meetup-core [154](R 154.1)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.models.annotations)(version>=1.5.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.apache.felix.webconsole.internal.core.BundlesServlet.doPost(BundlesServlet.java:359)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager.service(OsgiManager.java:563)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager$3.run(OsgiManager.java:465)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.felix.webconsole.internal.servlet.OsgiManager.service(OsgiManager.java:461)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
	at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:89)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
	at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:128)
	at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ist-rw** [comment]
I've built a fest Sling Launchpad 9 from 'trunk' just now and it works fine - all 155 bundles active, no wiring problems. But the 'composure.core.commons' bundle is exporting 'java.inject.*' and other bundles are doing this also... I've removed the export of 'java.inject' in the release 1.7.1 of the Composum Console. I hope this helps.

**Comment by drfits** [comment]
Thanks! Now everything is fine for me, every bundle imported javax.inject from **geronimo-atinject_1.0_spec**
